### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Prongs101/prj-rev-bwfs-dasmoto#6]
https://github.com/Prongs101/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L5-L21

This isn't easily read.

Conform your CSS to this style:

```css
selector {
  property: value;
  property: value;
}
```

Even if a rule only has a single property, avoid writing it all on one line.
